stages:          
  - build
  - sonarqube-check

build-node:
  image: node:latest
  stage: build
  script:
    - npm install ServeurSide/app-express/
    - npm install ClientSide/app-react/
    - node --check ServeurSide/app-express/*.js
    - node --check ClientSide/app-react/*.js


sonarqube-check:
  stage: sonarqube-check
  image: 
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: false
  only:
    - main